Add map to show details of fellows
MLH-Fellowship/pod-4.1.2-portfolio pull request #24
Opened 2021-10-05 16:06 UTC by NBNARADHYA

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Implements #12

2021-10-05 16:11 UTC, riteshsp2000 commented
This is a WIP PR... 

Work to be done:
- Configure markers on the map as per user location
- Create Card UI for the user (to be shown when clicked on the marker)

2021-10-06 06:26 UTC, riteshsp2000 commented
@wrussell1999 @yashika51 

This fixes issue #13 as well. The card that I created pops up after clicking on the marker. It shows the fellow name, description, technologies and socials.

2021-10-06 20:24 UTC, yashika51 requested changes

2021-10-06 20:24 UTC, yashika51 commented on _config.yml
> +accessToken: pk.eyJ1IjoibmJuYXJhZGh5YSIsImEiOiJja2xpdjc0eXQwMHY5MnhwNTVmbjlwY2phIn0.pS57OxYhcCZegQr4psnEdg
No secret tokens in main please. Use .env file.

2021-10-06 20:24 UTC, yashika51 commented on _sass/map.scss
> +}
I feel the description text looks very light, maybe experiment a bit to make it more clearly visible.

2021-10-06 20:24 UTC, yashika51 commented on _data/fellows.yml
> +    github: https://github.com/aaronosher
I can only see one pin in the UK when we have two people from same region, why is it not appearing in the map? Is it just for me?

2021-10-06 20:26 UTC, yashika51 requested changes

2021-10-06 20:26 UTC, yashika51 commented on _data/fellows.yml
> +    linkedin: https://www.linkedin.com/in/amanda-d-avria-287a017/
Clicking on any pin other than Will's pin doesn't display any information. This is strange....

2021-10-06 20:39 UTC, NBNARADHYA commented on _data/fellows.yml
> +    github: https://github.com/aaronosher
The fellows data has been modified for now, and their location coordinates don't exactly map correctly to their actual places. So pins are not accurate for now.

2021-10-06 20:42 UTC, NBNARADHYA commented on _data/fellows.yml
> +    linkedin: https://www.linkedin.com/in/amanda-d-avria-287a017/
It's working for me. I am not really sure why it doesn't for you.

2021-10-07 06:08 UTC, riteshsp2000 commented on _sass/map.scss
> +}
Okay sure... I'll try and experiment with few colors

2021-10-07 06:09 UTC, riteshsp2000 commented on _data/fellows.yml
> +    github: https://github.com/aaronosher
This looks nice!

2021-10-07 11:50 UTC, yashika51 commented on _data/fellows.yml
> +    github: https://github.com/aaronosher
Great job @NBNARADHYA!

2021-10-07 11:51 UTC, yashika51 approved these changes

2021-10-07 11:52 UTC, merged